# Generated by Django 5.0.1 on 2024-09-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeproduct',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
